
import { GoogleGenAI } from "@google/genai";

// Assume process.env.API_KEY is configured in the environment
const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  console.warn("API key for Gemini is not set. The Fetal Metrics Analyzer will not work.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

export const analyzeFetalMetrics = async (
  bpd: number,
  hc: number,
  ac: number,
  fl: number
): Promise<string> => {
  if (!API_KEY) {
    return Promise.reject(new Error("API_KEY not configured."));
  }

  const prompt = `
    Actúa como un experto en obstetricia y ginecología. Proporciona un análisis breve y preliminar, en un lenguaje claro y profesional, de las siguientes mediciones de biometría fetal.
    
    Mediciones:
    - Diámetro Biparietal (BPD): ${bpd} mm
    - Circunferencia Cefálica (HC): ${hc} mm
    - Circunferencia Abdominal (AC): ${ac} mm
    - Longitud del Fémur (FL): ${fl} mm
    
    Tu análisis debe:
    1. Explicar brevemente qué representa cada métrica (BPD, HC, AC, FL).
    2. Comentar de forma general sobre la proporcionalidad entre las medidas, especialmente la relación HC/AC.
    3. No debes proporcionar una edad gestacional estimada ni un peso fetal estimado. No debes emitir un diagnóstico definitivo.
    4. Concluye con un descargo de responsabilidad claro y visible.
    
    Formato de respuesta:
    [Párrafo de análisis conciso]
    ---
    [Texto del descargo de responsabilidad: "Esta es una herramienta informativa basada en IA y no reemplaza una consulta médica profesional. Los resultados deben ser interpretados por un especialista cualificado en el contexto clínico completo."]
    `;

  try {
    const response = await ai.models.generateContent({
        model: 'gemini-3-flash-preview',
        contents: prompt,
    });
    
    if (response.text) {
        return response.text;
    } else {
        throw new Error('No text was generated by the API.');
    }
  } catch (error) {
    console.error("Error calling Gemini API:", error);
    throw new Error("Failed to get analysis from Gemini API.");
  }
};
